import type { Metadata } from 'next';
import S from './page.module.scss';

export const metadata: Metadata = {
  title: '위치테스트',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <div className={S.layout}>{children}</div>;
}
